apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nfs-csi-node-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: nfs-csi-node
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nfs-csi-controller-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: nfs-csi-controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 5s